// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrv7lG6vSbK2h-m5_kfY-E6Tx11luGzE',
    appId: '1:319591226832:web:bfd5ab5e328bb7161e2dd5',
    messagingSenderId: '319591226832',
    projectId: 'ecommerce-app-7565',
    authDomain: 'ecommerce-app-7565.firebaseapp.com',
    storageBucket: 'ecommerce-app-7565.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGVv7aJeBAk49PFIBp_x5KN6P0m8xuPQ',
    appId: '1:319591226832:android:0072fead8bc848a61e2dd5',
    messagingSenderId: '319591226832',
    projectId: 'ecommerce-app-7565',
    storageBucket: 'ecommerce-app-7565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV5sE0JS_QBFw_aj17Q_TvCP68yP54EsQ',
    appId: '1:319591226832:ios:ff53a849c12337431e2dd5',
    messagingSenderId: '319591226832',
    projectId: 'ecommerce-app-7565',
    storageBucket: 'ecommerce-app-7565.firebasestorage.app',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:3be076689b6866ea0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-qfcmju8p2mbqre4rl5kufhr7dhs9hs33.apps.googleusercontent.com',
    iosClientId: '823307041176-7pen3ehk09mbnp7ukg6lm4a9sgr80pjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}